"""
Prompt templates for compliance agents
"""

from .templates import (
    TIKTOK_CONTEXT,
    SCREENING_PROMPT,
    RESEARCH_PROMPT,
    SCREENING_PROMPT,
    RESEARCH_PROMPT,
    VALIDATION_PROMPT,
    VALIDATION_PROMPT,
    COMPLIANCE_OUTPUT_SCHEMA
)

__all__ = [
    "TIKTOK_CONTEXT",
    "SCREENING_PROMPT",
    "RESEARCH_PROMPT",
    "SCREENING_PROMPT",
    "RESEARCH_PROMPT",
    "VALIDATION_PROMPT",
    "VALIDATION_PROMPT",
    "COMPLIANCE_OUTPUT_SCHEMA"
]