services:
  # FastAPI Backend Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - rag-network
    restart: unless-stopped

  # Postgres Database
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready -U postgres -d zero_shot"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Streamlit Frontend Application
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    depends_on:
      - app
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  chroma_data:
    driver: local
  postgres_data:
    driver: local

networks:
  rag-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
